"""elimine columna direccion

Revision ID: 9eed0a05473c
Revises: 526d9064d1f1
Create Date: 2023-07-26 22:46:00.080957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eed0a05473c'
down_revision = '526d9064d1f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.TEXT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
